version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
  api:
    build: .
    restart: always
    command: tail -f /dev/null
    volumes:
      - .:/root/apiv2
    ports:
      - "5566:22"
      - "8000:8000"
    environment:
      - LC_ALL=C.UTF-8
      - FLASK_APP=/root/apiv2/app.py
    links:
      - mysql
