version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
  api:
    build: .
    restart: always
    entrypoint: /root/api/run.sh
    volumes:
      - .:/root/api
    ports:
      - "5566:22"
      - "8000:8000"
    environment:
      - LC_ALL=C.UTF-8
      - FLASK_APP=/root/api/app.py
      - API_FOLDER=/root/api
    depends_on:
      - "mysql"
    links:
      - "mysql"
